### ISSUE TITLE
use of gauge

### ISSUE THREAD

**Issue by rokroskar** [mdawar/rq-exporter#15]
Hi there, thanks for this nice project! I'm curious about how you configure your `rq` queues to get useful statistics out of the gauges. The `finished` jobs are by default automatically cleaned so eventually the gauge loses track of them - or do you not care about historical numbers but really about the current state? Naively I would expect the summary metrics to be more appropriate, but perhaps I have a different use-case in mind.

**Comment by mdawar** [comment]
Hi,

We simply get the data using the `Queue` and `Worker` classes from the `rq` package when a request is made to the exporter by Prometheus, this data is about the current status of the workers and queues, `rq` does not provide any historical data.

This data is stored and managed by Prometheus, you can configure the [scrape interval](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) and the storage [retention time](https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects).

Check out the[ `utils.py`](https://github.com/mdawar/rq-exporter/blob/master/rq_exporter/utils.py) for the functions that fetch this data from `rq`.

I hope this helps.
