### ISSUE TITLE
Average queue latency

### ISSUE THREAD

**Issue by mkotsalainen** [mdawar/rq-exporter#24]
Hi! This project looks good. It would be good to get average latency per queue. I think it should be doable by exposing the total_working_time float that rq updates on every job.

Is this something that you've considered? If not, maybe I could try adding it.

**Comment by mdawar** [comment]
Hey,
Actually I haven't thought about it before, and yes please feel free to add this metric, I honestly don't have any free time to do it.
Thank you.

**Comment by mkotsalainen** [comment]
Ok here's the PR: https://github.com/mdawar/rq-exporter/pull/25

I'm running this on our servers.
