### ISSUE TITLE
Running exporter for multiple DBs within same Redis instance

### ISSUE THREAD

**Issue by dipeshprajapatixoxoday** [mdawar/rq-exporter#26]
First of all, thank you very much for sharing this with community.

I have one question here, how can I run the exporter for multiple DBs within the same redis instance? Thanks.

**Comment by mdawar** [comment]
Hi,

You have to run multiple instances of the exporter each one configured to use a separate db number.

If the exporter instances are running on the same host, you might also want to use a separate port for each exporter using the `-p, --port` cli arguments or `RQ_EXPORTER_PORT` env variable.

I hope that helps.

**Comment by dipeshprajapatixoxoday** [comment]
@mdawar This works. Thank you.
