### ISSUE TITLE
Cannot connect to sentinel with password auth

### ISSUE THREAD

**Issue by quom** [mdawar/rq-exporter#35]
suggestion: allow passing `password` as `sentinel_kwargs` to the sentinel connection

**Comment by mdawar** [comment]
Thanks for reporting, I'll look into it as soon as I can.

**Comment by quom** [comment]
Hi - I don't believe this is fixed quite yet:

[Here](https://github.com/mdawar/rq-exporter/blob/master/rq_exporter/utils.py#L59) the redis password is now not being passed into the redis connection. You need to add the `password=password` kwarg to pass the password to the redis connection too.

**Comment by mdawar** [comment]
Sorry about that, I'll fix it.

**Comment by mdawar** [comment]
@quom I've published a new version [v2.1.2](https://github.com/mdawar/rq-exporter/releases/tag/v2.1.2) with this fix.
