### ISSUE TITLE
Version lock to rq==1.4.1

### ISSUE THREAD

**Issue by telemmaite** [mdawar/rq-exporter#5]
Hello, would it be possible to apply loser version restriction on **rq** dependency?

Could be `rq>1.4` , or if version lock is needed to target the latest **rq** ( as of writing this 1.5.2) which contains a couple of important bugfixes that I need.

**Comment by mdawar** [comment]
Hello,

I have published a new release [v1.4.0](https://github.com/mdawar/rq-exporter/releases/tag/v1.4.0) with **rq** `v1.5.2`.
