### ISSUE TITLE
Improve grafana dashboard

### ISSUE THREAD

**Issue by andrii29** [mdawar/rq-exporter#7]
Hello,
Please add **queue** variable in grafana dashboard to be able to filter all graphs by single click

Regards,
Andrii

**Comment by mdawar** [comment]
Hello,

Thank you for your suggestion, I will add it when I get some free time.

By the way this dashboard is just for demonstration, you can customize it or create your own.

**Comment by mdawar** [comment]
Hi,

I've added the queue variable, it's only used for the "Jobs by status" panels as it's not relevant for the other ones.
